version: '3.5' # We use version 3.5 syntax
services: # Here we define our service(s)
    angular-service: # The name of the service
      container_name: angularcontainer  # Container name
      build: ./bpmn2imds-web-ui # Location of our Dockerfile
      volumes: # Volume binding
        - './bpmn2imds-web-ui:/usr/src/app' 
      ports: 
        - '4200:1234' # Port mapping